# Regression Example in TensorFlow (with TensorBoard)
Predicting house prices in Boston, Massachusetts while logging results for TensorBoard

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/jonkrohn/DLTFpT/blob/master/notebooks/regression_in_tensorflow_with_tensorboard.ipynb)

#### Load dependencies

In [1]:
import numpy as np
from tensorflow.keras.datasets import boston_housing 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout 
from tensorflow.keras.layers import BatchNormalization 
from tensorflow.keras.callbacks import ModelCheckpoint 
from tensorflow.keras.callbacks import TensorBoard # new!  
import os 

#### Load data

In [2]:
(X_train, y_train), (X_valid, y_valid) = boston_housing.load_data()

In [3]:
X_train.shape

(404, 13)

In [4]:
X_valid.shape

(102, 13)

In [5]:
X_train[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [6]:
y_train[0]

15.2

#### Design neural network architecture

In [7]:
model = Sequential()

model.add(Dense(32, input_dim=13, activation='relu'))
model.add(BatchNormalization())

model.add(Dense(16, activation='relu'))
model.add(BatchNormalization())
model.add(Dropout(0.2))

model.add(Dense(1, activation='linear'))

/Users/sshivagangeprakash/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization             │ (None, 32)             │           128 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ batch_normalization_1           │ (None, 16)             │            64 │
│ (BatchNormalization)            │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,185 (4.63 KB)

 Trainable params: 1,089 (4.25 KB)

 Non-trainable params: 96 (384.00 B)

#### Configure Model

In [9]:
model.compile(loss='mean_squared_error', optimizer='adam', )

In [10]:
output_dir = 'model_output/'

In [11]:
run_name = 'regression_baseline'
output_path = output_dir + run_name

In [12]:
if not os.path.exists(output_path):
    os.makedirs(output_path)

In [13]:
modelcheckpoint = ModelCheckpoint(output_path + '/weights.{epoch:02d}.weights.h5', # decimal integers
                                  save_weights_only=True) # otherwise full model is saved

In [14]:
# similar to modelcheckpoints need a output directory, tensorboard also needs output directory where epochs output is stored.
tensorboard = TensorBoard(log_dir='logs/' + run_name)

#### Train!

In [15]:
# In callbacks we have to pass the tensorboard.
model.fit(X_train, y_train, 
          batch_size=8, epochs=32, verbose=1, 
          validation_data=(X_valid, y_valid),
          callbacks=[modelcheckpoint, tensorboard]) 

Epoch 1/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 594.2388 - val_loss: 671.1261
Epoch 2/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 581.5126 - val_loss: 628.2557
Epoch 3/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - loss: 560.9124 - val_loss: 597.7372
Epoch 4/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - loss: 504.7204 - val_loss: 566.1986
Epoch 5/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - loss: 493.6090 - val_loss: 532.5129
Epoch 6/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - loss: 473.5441 - val_loss: 504.4836
Epoch 7/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - loss: 413.2005 - val_loss: 521.5862
Epoch 8/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - loss: 378.4223 - val_loss: 622.4077
Epoch 9/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - loss: 343.8732 - val_loss: 638.2480
Epoch 10/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - loss: 319.1817 - val_loss: 425.7594
Epoch 11/32
51/51 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - loss: 260.6948 - val_loss: 401.6861
Epoch 12/32


#### Performing inference

In [16]:
model.load_weights(output_path + '/weights.20.weights.h5')

In [17]:
X_valid[42]

array([  9.32909,   0.     ,  18.1    ,   0.     ,   0.713  ,   6.185  ,
        98.7    ,   2.2616 ,  24.     , 666.     ,  20.2    , 396.9    ,
        18.13   ])

In [18]:
y_valid[42]

14.1

In [19]:
model.predict(np.reshape(X_valid[42], [1, 13]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[11.78629]], dtype=float32)

### After the program is executed, follow below steps
1. Open terminal in your machine.
2. Navigate to folder your notebooks are available. 
3. In the folder, check is the `logs` directory available
4. Then run below command.
    `tensorboard --logdir='logs/' --port 6006`
5. Now open browser and enter
    `http://localhost:6006/`
 
